# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false
    handle_all_throwables: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native
    cache:
        pools:
            company_pool:
                adapter: cache.adapter.filesystem
                default_lifetime: 3600
            history_pool:
                adapter: cache.adapter.filesystem
                default_lifetime: 3600
            
    #esi: true
    #fragments: true
    php_errors:
        log: true
    http_client:
        scoped_clients:
            rapid.history.client:
                scope: '%env(RAPID_HISTORY_SCHEME)%://%env(RAPID_HISTORY_HOST)%'
                base_uri: '%env(RAPID_HISTORY_SCHEME)%://%env(RAPID_HISTORY_HOST)%'
                headers:
                    X-RapidAPI-Host: '%env(RAPID_HISTORY_HOST)%'
                    X-RapidAPI-Key: '%env(RAPID_HISTORY_SECRET_KEY)%'
                    Accept: 'application/json'
            rapid.company.client:
                scope: '%env(RAPID_COMPANY_HOST)%'
                base_uri: '%env(RAPID_COMPANY_HOST)%'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
