jms_serializer:
    default_context:
        serialization:
            serialize_null: true
    property_naming:
        id: 'jms_serializer.identical_property_naming_strategy'
    visitors:
        xml_serialization:
            format_output: '%kernel.debug%'
